package com.coms309.nutrifit.util;

public enum Equipment {
    NONE, EZ_CURL_BAR, BARBELL, DUMBBELL, GYM_MAT, EXERCISE_BALL, MEDICINE_BALL, PULL_UP_BAR, BENCH, INCLINE_BENCH,
    KETTLEBELL, MACHINE, CABLE, BANDS, FOAM_ROLL, OTHER
}
